volumes:
  caddy_data: {}

services:
  caddy:
    # Unlike the official caddy image, this is falling-down-easy to configure as a lets-encrypt-certificate-fetching
    # reverse proxy.
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    restart: unless-stopped
    profiles:
      - prod
