# Generated by Django 5.2.6 on 2025-09-11 18:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('in_progress', models.BooleanField(default=True)),
                ('moves', models.CharField(null=True)),
                ('black_smartness', models.PositiveSmallIntegerField(default=10)),
            ],
        ),
    ]
