# Generated by Django 5.2.5 on 2025-08-16 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='board_fen',
        ),
        migrations.AddField(
            model_name='game',
            name='moves',
            field=models.CharField(null=True),
        ),
    ]
