# Generated by Django 5.2.5 on 2025-08-17 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_game_board_fen_game_moves'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='computer_think_time_ms',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
