# Generated by Django 5.2.5 on 2025-08-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_game_in_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='computer_think_time_ms',
        ),
        migrations.AddField(
            model_name='game',
            name='black_smartness',
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
