# Generated by Django 6.0 on 2026-01-13 02:16

import django_chess.name_generator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_game_computer_think_time_ms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='name',
            field=models.CharField(default=django_chess.name_generator.generate_game_name, max_length=100),
        ),
    ]
