# Generated by Django 6.0 on 2026-01-13 15:40

from django.db import migrations


def update_game_names(apps, schema_editor):
    """Update all existing games with UUID-based deterministic names."""
    from django_chess.name_generator import generate_game_name

    Game = apps.get_model('app', 'Game')
    for game in Game.objects.all():
        # Generate deterministic name based on UUID
        game.name = generate_game_name(seed=game.id.int)
        game.save(update_fields=['name'])


def reverse_migration(apps, schema_editor):
    """No-op reverse migration - we can't reliably restore old names."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_game_name'),
    ]

    operations = [
        migrations.RunPython(update_game_names, reverse_migration),
    ]
