# Generated by Django 6.0 on 2026-01-14 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_add_timestamps'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'get_latest_by': 'modified'},
        ),
    ]
